#ifndef EXTERNAL_LORA_GATEWAY_5_0_1_LORA_GATEWAY_LIBLORAGW_INC_CONFIG
#define EXTERNAL_LORA_GATEWAY_5_0_1_LORA_GATEWAY_LIBLORAGW_INC_CONFIG

#define LIBLORAGW_VERSION "2.1.0"


#endif /* EXTERNAL_LORA_GATEWAY_5_0_1_LORA_GATEWAY_LIBLORAGW_INC_CONFIG */
